# The URL the site will be built for
base_url = "https://deploy-vercel-five.vercel.app/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"

taxonomies = [
{name="tags", paginate_by = 5},
]
[slugify]
paths = "on"
taxonomies = "on"
anchors = "off"

[extra]
# Put all your custom variables here
